name: phone_field
description: "A Flutter package for phone number input field."
version: 0.0.1
homepage: https://github.com/Ddtarsariya/Phone-Field

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  country_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: