import 'package:phone_field/models/country_model.dart';

const List<Country> defaultCountries = [
  Country(name: "Andorra", dialCode: "+376", code: "AD"),
  Country(name: "United Arab Emirates", dialCode: "+971", code: "AE"),
  Country(name: "Afghanistan", dialCode: "+93", code: "AF"),
  Country(name: "Antigua and Barbuda", dialCode: "+1-268", code: "AG"),
  Country(name: "Anguilla", dialCode: "+1-264", code: "AI"),
  Country(name: "Albania", dialCode: "+355", code: "AL"),
  Country(name: "Armenia", dialCode: "+374", code: "AM"),
  Country(name: "Angola", dialCode: "+244", code: "AO"),
  Country(name: "Antarctica", dialCode: "+672", code: "AQ"),
  Country(name: "Argentina", dialCode: "+54", code: "AR"),
  Country(name: "American Samoa", dialCode: "+1-684", code: "AS"),
  Country(name: "Austria", dialCode: "+43", code: "AT"),
  Country(name: "Australia", dialCode: "+61", code: "AU"),
  Country(name: "Aruba", dialCode: "+297", code: "AW"),
  Country(name: "Åland Islands", dialCode: "+358-18", code: "AX"),
  Country(name: "Azerbaijan", dialCode: "+994", code: "AZ"),
  Country(name: "Bosnia and Herzegovina", dialCode: "+387", code: "BA"),
  Country(name: "Barbados", dialCode: "+1-246", code: "BB"),
  Country(name: "Bangladesh", dialCode: "+880", code: "BD"),
  Country(name: "Belgium", dialCode: "+32", code: "BE"),
  Country(name: "Burkina Faso", dialCode: "+226", code: "BF"),
  Country(name: "Bulgaria", dialCode: "+359", code: "BG"),
  Country(name: "Bahrain", dialCode: "+973", code: "BH"),
  Country(name: "Burundi", dialCode: "+257", code: "BI"),
  Country(name: "Benin", dialCode: "+229", code: "BJ"),
  Country(name: "Saint Barthélemy", dialCode: "+590", code: "BL"),
  Country(name: "Bermuda", dialCode: "+1-441", code: "BM"),
  Country(name: "Brunei Darussalam", dialCode: "+673", code: "BN"),
  Country(
      name: "Bolivia, Plurinational State of", dialCode: "+591", code: "BO"),
  Country(name: "Caribbean Netherlands", dialCode: "+599", code: "BQ"),
  Country(name: "Brazil", dialCode: "+55", code: "BR"),
  Country(name: "Bahamas", dialCode: "+1-242", code: "BS"),
  Country(name: "Bhutan", dialCode: "+975", code: "BT"),
  Country(name: "Bouvet Island", dialCode: "", code: "BV"),
  Country(name: "Botswana", dialCode: "+267", code: "BW"),
  Country(name: "Belarus", dialCode: "+375", code: "BY"),
  Country(name: "Belize", dialCode: "+501", code: "BZ"),
  Country(name: "Canada", dialCode: "+1", code: "CA"),
  Country(name: "Cocos (Keeling) Islands", dialCode: "+61", code: "CC"),
  Country(
      name: "Congo, the Democratic Republic of the",
      dialCode: "+243",
      code: "CD"),
  Country(name: "Central African Republic", dialCode: "+236", code: "CF"),
  Country(name: "Republic of the Congo", dialCode: "+242", code: "CG"),
  Country(name: "Switzerland", dialCode: "+41", code: "CH"),
  Country(name: "Côte d'Ivoire", dialCode: "+225", code: "CI"),
  Country(name: "Cook Islands", dialCode: "+682", code: "CK"),
  Country(name: "Chile", dialCode: "+56", code: "CL"),
  Country(name: "Cameroon", dialCode: "+237", code: "CM"),
  Country(
      name: "China (People's Republic of China)", dialCode: "+86", code: "CN"),
  Country(name: "Colombia", dialCode: "+57", code: "CO"),
  Country(name: "Costa Rica", dialCode: "+506", code: "CR"),
  Country(name: "Cuba", dialCode: "+53", code: "CU"),
  Country(name: "Cape Verde", dialCode: "+238", code: "CV"),
  Country(name: "Curaçao", dialCode: "+599", code: "CW"),
  Country(name: "Christmas Island", dialCode: "+61", code: "CX"),
  Country(name: "Cyprus", dialCode: "+357", code: "CY"),
  Country(name: "Czech Republic", dialCode: "+420", code: "CZ"),
  Country(name: "Germany", dialCode: "+49", code: "DE"),
  Country(name: "Djibouti", dialCode: "+253", code: "DJ"),
  Country(name: "Denmark", dialCode: "+45", code: "DK"),
  Country(name: "Dominica", dialCode: "+1-767", code: "DM"),
  Country(
      name: "Dominican Republic",
      dialCode: "+1-809, +1-829, +1-849",
      code: "DO"),
  Country(name: "Algeria", dialCode: "+213", code: "DZ"),
  Country(name: "Ecuador", dialCode: "+593", code: "EC"),
  Country(name: "Estonia", dialCode: "+372", code: "EE"),
  Country(name: "Egypt", dialCode: "+20", code: "EG"),
  Country(name: "Western Sahara", dialCode: "+212", code: "EH"),
  Country(name: "Eritrea", dialCode: "+291", code: "ER"),
  Country(name: "Spain", dialCode: "+34", code: "ES"),
  Country(name: "Ethiopia", dialCode: "+251", code: "ET"),
  Country(name: "Europe", dialCode: "", code: "EU"),
  Country(name: "Finland", dialCode: "+358", code: "FI"),
  Country(name: "Fiji", dialCode: "+679", code: "FJ"),
  Country(name: "Falkland Islands (Malvinas)", dialCode: "+500", code: "FK"),
  Country(
      name: "Micronesia, Federated States of", dialCode: "+691", code: "FM"),
  Country(name: "Faroe Islands", dialCode: "+298", code: "FO"),
  Country(name: "France", dialCode: "+33", code: "FR"),
  Country(name: "Gabon", dialCode: "+241", code: "GA"),
  Country(name: "England", dialCode: "+44", code: "GB-ENG"),
  Country(name: "Northern Ireland", dialCode: "+44", code: "GB-NIR"),
  Country(name: "Scotland", dialCode: "+44", code: "GB-SCT"),
  Country(name: "Wales", dialCode: "+44", code: "GB-WLS"),
  Country(name: "United Kingdom", dialCode: "+44", code: "GB"),
  Country(name: "Grenada", dialCode: "+1-473", code: "GD"),
  Country(name: "Georgia", dialCode: "+995", code: "GE"),
  Country(name: "French Guiana", dialCode: "+594", code: "GF"),
  Country(name: "Guernsey", dialCode: "+44", code: "GG"),
  Country(name: "Ghana", dialCode: "+233", code: "GH"),
  Country(name: "Gibraltar", dialCode: "+350", code: "GI"),
  Country(name: "Greenland", dialCode: "+299", code: "GL"),
  Country(name: "Gambia", dialCode: "+220", code: "GM"),
  Country(name: "Guinea", dialCode: "+224", code: "GN"),
  Country(name: "Guadeloupe", dialCode: "+590", code: "GP"),
  Country(name: "Equatorial Guinea", dialCode: "+240", code: "GQ"),
  Country(name: "Greece", dialCode: "+30", code: "GR"),
  Country(
      name: "South Georgia and the South Sandwich Islands",
      dialCode: "+500",
      code: "GS"),
  Country(name: "Guatemala", dialCode: "+502", code: "GT"),
  Country(name: "Guam", dialCode: "+1-671", code: "GU"),
  Country(name: "Guinea-Bissau", dialCode: "+245", code: "GW"),
  Country(name: "Guyana", dialCode: "+592", code: "GY"),
  Country(name: "Hong Kong", dialCode: "+852", code: "HK"),
  Country(name: "Heard Island and McDonald Islands", dialCode: "", code: "HM"),
  Country(name: "Honduras", dialCode: "+504", code: "HN"),
  Country(name: "Croatia", dialCode: "+385", code: "HR"),
  Country(name: "Haiti", dialCode: "+509", code: "HT"),
  Country(name: "Hungary", dialCode: "+36", code: "HU"),
  Country(name: "Indonesia", dialCode: "+62", code: "ID"),
  Country(name: "Ireland", dialCode: "+353", code: "IE"),
  Country(name: "Israel", dialCode: "+972", code: "IL"),
  Country(name: "Isle of Man", dialCode: "+44", code: "IM"),
  Country(name: "India", dialCode: "+91", code: "IN"),
  Country(name: "British Indian Ocean Territory", dialCode: "+246", code: "IO"),
  Country(name: "Iraq", dialCode: "+964", code: "IQ"),
  Country(name: "Iran, Islamic Republic of", dialCode: "+98", code: "IR"),
  Country(name: "Iceland", dialCode: "+354", code: "IS"),
  Country(name: "Italy", dialCode: "+39", code: "IT"),
  Country(name: "Jersey", dialCode: "+44", code: "JE"),
  Country(name: "Jamaica", dialCode: "+1-876", code: "JM"),
  Country(name: "Jordan", dialCode: "+962", code: "JO"),
  Country(name: "Japan", dialCode: "+81", code: "JP"),
  Country(name: "Kenya", dialCode: "+254", code: "KE"),
  Country(name: "Kyrgyzstan", dialCode: "+996", code: "KG"),
  Country(name: "Cambodia", dialCode: "+855", code: "KH"),
  Country(name: "Kiribati", dialCode: "+686", code: "KI"),
  Country(name: "Comoros", dialCode: "+269", code: "KM"),
  Country(name: "Saint Kitts and Nevis", dialCode: "+1-869", code: "KN"),
  Country(
      name: "Korea, Democratic People's Republic of",
      dialCode: "+850",
      code: "KP"),
  Country(name: "Korea, Republic of", dialCode: "+82", code: "KR"),
  Country(name: "Kuwait", dialCode: "+965", code: "KW"),
  Country(name: "Cayman Islands", dialCode: "+1-345", code: "KY"),
  Country(name: "Kazakhstan", dialCode: "+7", code: "KZ"),
  Country(
      name: "Laos (Lao People's Democratic Republic)",
      dialCode: "+856",
      code: "LA"),
  Country(name: "Lebanon", dialCode: "+961", code: "LB"),
  Country(name: "Saint Lucia", dialCode: "+1-758", code: "LC"),
  Country(name: "Liechtenstein", dialCode: "+423", code: "LI"),
  Country(name: "Sri Lanka", dialCode: "+94", code: "LK"),
  Country(name: "Liberia", dialCode: "+231", code: "LR"),
  Country(name: "Lesotho", dialCode: "+266", code: "LS"),
  Country(name: "Lithuania", dialCode: "+370", code: "LT"),
  Country(name: "Luxembourg", dialCode: "+352", code: "LU"),
  Country(name: "Latvia", dialCode: "+371", code: "LV"),
  Country(name: "Libya", dialCode: "+218", code: "LY"),
  Country(name: "Morocco", dialCode: "+212", code: "MA"),
  Country(name: "Monaco", dialCode: "+377", code: "MC"),
  Country(name: "Moldova, Republic of", dialCode: "+373", code: "MD"),
  Country(name: "Montenegro", dialCode: "+382", code: "ME"),
  Country(name: "Saint Martin", dialCode: "+590", code: "MF"),
  Country(name: "Madagascar", dialCode: "+261", code: "MG"),
  Country(name: "Marshall Islands", dialCode: "+692", code: "MH"),
  Country(name: "North Macedonia", dialCode: "+389", code: "MK"),
  Country(name: "Mali", dialCode: "+223", code: "ML"),
  Country(name: "Myanmar", dialCode: "+95", code: "MM"),
  Country(name: "Mongolia", dialCode: "+976", code: "MN"),
  Country(name: "Macao", dialCode: "+853", code: "MO"),
  Country(name: "Northern Mariana Islands", dialCode: "+1-670", code: "MP"),
  Country(name: "Martinique", dialCode: "+596", code: "MQ"),
  Country(name: "Mauritania", dialCode: "+222", code: "MR"),
  Country(name: "Montserrat", dialCode: "+1-664", code: "MS"),
  Country(name: "Malta", dialCode: "+356", code: "MT"),
  Country(name: "Mauritius", dialCode: "+230", code: "MU"),
  Country(name: "Maldives", dialCode: "+960", code: "MV"),
  Country(name: "Malawi", dialCode: "+265", code: "MW"),
  Country(name: "Mexico", dialCode: "+52", code: "MX"),
  Country(name: "Malaysia", dialCode: "+60", code: "MY"),
  Country(name: "Mozambique", dialCode: "+258", code: "MZ"),
  Country(name: "Namibia", dialCode: "+264", code: "NA"),
  Country(name: "New Caledonia", dialCode: "+687", code: "NC"),
  Country(name: "Niger", dialCode: "+227", code: "NE"),
  Country(name: "Norfolk Island", dialCode: "+672", code: "NF"),
  Country(name: "Nigeria", dialCode: "+234", code: "NG"),
  Country(name: "Nicaragua", dialCode: "+505", code: "NI"),
  Country(name: "Netherlands", dialCode: "+31", code: "NL"),
  Country(name: "Norway", dialCode: "+47", code: "NO"),
  Country(name: "Nepal", dialCode: "+977", code: "NP"),
  Country(name: "Nauru", dialCode: "+674", code: "NR"),
  Country(name: "Niue", dialCode: "+683", code: "NU"),
  Country(name: "New Zealand", dialCode: "+64", code: "NZ"),
  Country(name: "Oman", dialCode: "+968", code: "OM"),
  Country(name: "Panama", dialCode: "+507", code: "PA"),
  Country(name: "Peru", dialCode: "+51", code: "PE"),
  Country(name: "French Polynesia", dialCode: "+689", code: "PF"),
  Country(name: "Papua New Guinea", dialCode: "+675", code: "PG"),
  Country(name: "Philippines", dialCode: "+63", code: "PH"),
  Country(name: "Pakistan", dialCode: "+92", code: "PK"),
  Country(name: "Poland", dialCode: "+48", code: "PL"),
  Country(name: "Saint Pierre and Miquelon", dialCode: "+508", code: "PM"),
  Country(name: "Pitcairn", dialCode: "+870", code: "PN"),
  Country(name: "Puerto Rico", dialCode: "+1-787, +1-939", code: "PR"),
  Country(name: "Palestine", dialCode: "+970", code: "PS"),
  Country(name: "Portugal", dialCode: "+351", code: "PT"),
  Country(name: "Palau", dialCode: "+680", code: "PW"),
  Country(name: "Paraguay", dialCode: "+595", code: "PY"),
  Country(name: "Qatar", dialCode: "+974", code: "QA"),
  Country(name: "Réunion", dialCode: "+262", code: "RE"),
  Country(name: "Romania", dialCode: "+40", code: "RO"),
  Country(name: "Serbia", dialCode: "+381", code: "RS"),
  Country(name: "Russian Federation", dialCode: "+7", code: "RU"),
  Country(name: "Rwanda", dialCode: "+250", code: "RW"),
  Country(name: "Saudi Arabia", dialCode: "+966", code: "SA"),
  Country(name: "Solomon Islands", dialCode: "+677", code: "SB"),
  Country(name: "Seychelles", dialCode: "+248", code: "SC"),
  Country(name: "Sudan", dialCode: "+249", code: "SD"),
  Country(name: "Sweden", dialCode: "+46", code: "SE"),
  Country(name: "Singapore", dialCode: "+65", code: "SG"),
  Country(
      name: "Saint Helena, Ascension and Tristan da Cunha",
      dialCode: "+290",
      code: "SH"),
  Country(name: "Slovenia", dialCode: "+386", code: "SI"),
  Country(name: "Svalbard and Jan Mayen Islands", dialCode: "+47", code: "SJ"),
  Country(name: "Slovakia", dialCode: "+421", code: "SK"),
  Country(name: "Sierra Leone", dialCode: "+232", code: "SL"),
  Country(name: "San Marino", dialCode: "+378", code: "SM"),
  Country(name: "Senegal", dialCode: "+221", code: "SN"),
  Country(name: "Somalia", dialCode: "+252", code: "SO"),
  Country(name: "Suriname", dialCode: "+597", code: "SR"),
  Country(name: "South Sudan", dialCode: "+211", code: "SS"),
  Country(name: "Sao Tome and Principe", dialCode: "+239", code: "ST"),
  Country(name: "El Salvador", dialCode: "+503", code: "SV"),
  Country(name: "Sint Maarten (Dutch part)", dialCode: "+1-721", code: "SX"),
  Country(name: "Syrian Arab Republic", dialCode: "+963", code: "SY"),
  Country(name: "Swaziland", dialCode: "+268", code: "SZ"),
  Country(name: "Turks and Caicos Islands", dialCode: "+1-649", code: "TC"),
  Country(name: "Chad", dialCode: "+235", code: "TD"),
  Country(name: "French Southern Territories", dialCode: "+262", code: "TF"),
  Country(name: "Togo", dialCode: "+228", code: "TG"),
  Country(name: "Thailand", dialCode: "+66", code: "TH"),
  Country(name: "Tajikistan", dialCode: "+992", code: "TJ"),
  Country(name: "Tokelau", dialCode: "+690", code: "TK"),
  Country(name: "Timor-Leste", dialCode: "+670", code: "TL"),
  Country(name: "Turkmenistan", dialCode: "+993", code: "TM"),
  Country(name: "Tunisia", dialCode: "+216", code: "TN"),
  Country(name: "Tonga", dialCode: "+676", code: "TO"),
  Country(name: "Turkey", dialCode: "+90", code: "TR"),
  Country(name: "Trinidad and Tobago", dialCode: "+1-868", code: "TT"),
  Country(name: "Tuvalu", dialCode: "+688", code: "TV"),
  Country(name: "Taiwan (Republic of China)", dialCode: "+886", code: "TW"),
  Country(name: "Tanzania, United Republic of", dialCode: "+255", code: "TZ"),
  Country(name: "Ukraine", dialCode: "+380", code: "UA"),
  Country(name: "Uganda", dialCode: "+256", code: "UG"),
  Country(name: "US Minor Outlying Islands", dialCode: "+1", code: "UM"),
  Country(name: "United States", dialCode: "+1", code: "US"),
  Country(name: "Uruguay", dialCode: "+598", code: "UY"),
  Country(name: "Uzbekistan", dialCode: "+998", code: "UZ"),
  Country(name: "Holy See (Vatican City State)", dialCode: "+379", code: "VA"),
  Country(
      name: "Saint Vincent and the Grenadines", dialCode: "+1-784", code: "VC"),
  Country(
      name: "Venezuela, Bolivarian Republic of", dialCode: "+58", code: "VE"),
  Country(name: "Virgin Islands, British", dialCode: "+1-284", code: "VG"),
  Country(name: "Virgin Islands, U.S.", dialCode: "+1-340", code: "VI"),
  Country(name: "Vietnam", dialCode: "+84", code: "VN"),
  Country(name: "Vanuatu", dialCode: "+678", code: "VU"),
  Country(name: "Wallis and Futuna Islands", dialCode: "+681", code: "WF"),
  Country(name: "Samoa", dialCode: "+685", code: "WS"),
  Country(name: "Kosovo", dialCode: "+383", code: "XK"),
  Country(name: "Yemen", dialCode: "+967", code: "YE"),
  Country(name: "Mayotte", dialCode: "+262", code: "YT"),
  Country(name: "South Africa", dialCode: "+27", code: "ZA"),
  Country(name: "Zambia", dialCode: "+260", code: "ZM"),
  Country(name: "Zimbabwe", dialCode: "+263", code: "ZW"),
];
